### ISSUE TITLE
isToday无法触发？

### ISSUE THREAD

**Issue by pandaljf** [zwhGithub/vue-calendar#17]
按照官方写下的demo例子，isToday事件没有触发？观察在线demo好像也没有触发isToday？

**Comment by zwhGithub** [comment]
可能平时更新把这个属性给漏了，晚上加一下

**Comment by zwhGithub** [comment]
已经加上了 如果有需要你可以继续使用。有问题可以在反馈

**Comment by pandaljf** [comment]
@zwhGithub  升级到2.5.6发现组件内部报错了，请务必解决下
![9rp3q82 7 vkcnx y0 x0a](https://user-images.githubusercontent.com/28444243/41195359-586fed72-6c5e-11e8-8dd4-c4077f83c8de.png)
